# Training configuration
trainer:
  max_epochs: 30
  accelerator: "auto"  # Uses GPU if available, otherwise CPU
  devices: 1
  precision: "32-true"  # Options: "32-true", "16-mixed", "bf16-mixed"
  deterministic: true
  gradient_clip_val: 1.0

optimizer:
  name: "adam"  # Options: adam, sgd, adamw
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  name: "reduce_on_plateau"  # Options: reduce_on_plateau, cosine_annealing, step
  patience: 3
  factor: 0.5
  min_lr: 1e-6

dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: true

early_stopping:
  monitor: "val_loss"
  patience: 7
  mode: "min" 